apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: v0rnsto0o-python 
  janus-idp.io/tekton: v0rnsto0o-python
  backstage.io/kubernetes-id: v0rnsto0o-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v0rnsto0o-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  