apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v0rnsto0o-python
  janus-idp.io/tekton: v0rnsto0o-python
  backstage.io/kubernetes-id: v0rnsto0o-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v0rnsto0o-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
